### ISSUE TITLE
Forcefully change file permissions upon transfer (SCP Upload)

### ISSUE THREAD

**Issue by wsmd** [aptonic/dropzone-user-scripts#28]
I'm having this weird issue with SCP Upload.

Permissions for **images** uploaded using this script is set to  `-rw-------`. Therefore, they can't be accessed with the URL returned by Dropzone.

![screen shot 2015-08-05 at 6 12 48 pm](https://cloud.githubusercontent.com/assets/2100222/9099295/980d90e6-3b9d-11e5-9c21-bd5696a7785f.png)

Since a direct URL is being returned after uploading a file using the **SCP Upload** script, it would make more sense to forcefully change the file's permission on the server to `644` (`-rw-r--r--`) to make sure it's accessible.

To my knowledge, it would only take a simple `ssh` + `chmod` command to solve this.

I hope this will help:
http://superuser.com/questions/291835/change-permissions-upon-uploading-with-scp

**Comment by aptonic** [comment]
Is this under Dropzone 3 and the newest version (1.3) of the SCP Upload action? I notice that you've filed this under the old Dropzone 2 actions repository rather than the current Dropzone 3 actions repo at https://github.com/aptonic/dropzone3-actions so thought I'd check. 

If this is happening on the old Dropzone 2 action then can you please retest this under Dropzone 3 with the updated SCP action installed from this page: https://aptonic.com/dropzone3/actions - If the problem still exists under Dropzone 3 with the new action then I will investigate this further.

The SCP action in this repository is well and truly deprecated. This outdated repository will be removed soon.

**Comment by wsmd** [comment]
My bad! Sorry about that.
It's occurring under Dropzone (3) and SCP Upload action (1.3) I'll open a new issue under the current repo

**Comment by aptonic** [comment]
Thanks, that'd be great!
